spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transcriptions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

grpc:
  server:
    address: 0.0.0.0
    port: 50052
jwt:
  secret: asdhuasdyouwfoybbsfdasdhuasdyouwfoybbsfdasdhuasdyouwfoybbsfdasdhuasdyouwfoybbsfdasdhuasdyouwfoybbsfd
  expiration: 86400000 # 1 Tag