spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transcriptions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

grpc:
  server:
    address: 0.0.0.0
    port: 50052
