OPENAI_ENDPOINT: https://engelbert.ip-ddns.com/v1
OPENAI_TOKEN: REDACTED
OPENAI_MODEL: deepseek-r1:1.5b

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transcriptions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8082
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

grpc:
  server:
    port: 50053
    reflection-service-enabled: true
jwt:
  secret: b2c973b295174fadbbf36d98460c5a8a4ddf47173dc8b7d85a1b728d3e6e4e2b
  expiration: 86400000 # 1 Tag