OPENAI_ENDPOINT: https://engelbert.ip-ddns.com
OPENAI_TOKEN: qhps7UQwMVG9zhxzq2vzHYR1YiDWd6xRptf729y16BfZ5WSmUO8mrb1lwFtQR6dr

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transcriptions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8082

